Fix big question mark
Splitit/Splitit.Plugins.WooCommerce pull request #40
Opened 2020-09-17 21:28 UTC by AlexeyKovalkovvv

2020-09-21 18:07 UTC, sixg requested changes
@AlexeyKovalkovvv Please review the changes and remove conflicts before the PR can be merged.

2020-09-21 18:07 UTC, sixg commented on splitit-installment-payments-enabler/assets/css/splitit-front.css
> +div.payment_box.payment_method_splitit img.tell-me-more-image {max-height: 100% !important;}
@AlexeyKovalkovvv has this been tested ?

2020-09-22 17:05 UTC, AlexeyKovalkovvv commented on splitit-installment-payments-enabler/assets/css/splitit-front.css
> +div.payment_box.payment_method_splitit img.tell-me-more-image {max-height: 100% !important;}
Removed locally, it works fine without this line

2020-09-22 17:10 UTC, sixg commented on splitit-installment-payments-enabler/assets/css/splitit-front.css
> +div.payment_box.payment_method_splitit img.tell-me-more-image {max-height: 100% !important;}
ok, thanks for confirmation.

2020-09-22 17:15 UTC, sixg approved these changes
@AlexeyKovalkovvv tested it properly and confirmed that the PR can now be merged. The changes seems to be fine. Staging needs to be tested again after the merge.
PR approved.

2020-09-22 17:20 UTC, merged